In [1]:
import pandas as pd

In [3]:
# reading the data
energy_df = pd.read_csv('data/energy.csv')
water = pd.read_csv('data/wc.csv')

In [4]:
energy_df.head(
    
)

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,alexandria egypt,2022-01-01,17.0,6.0,11.8,17.0,6.0,11.8,10.0,88.1,...,12.2,6,NaN,2022-01-01T06:59:09,2022-01-01T17:08:45,0.95,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,"62318099999,62360199999,HEAX,HEBA"
1,alexandria egypt,2022-01-02,19.0,9.0,14.3,19.0,7.6,14.2,11.4,83.7,...,9.6,5,NaN,2022-01-02T06:59:22,2022-01-02T17:09:29,0.00,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"62318099999,62360199999,HEAX,HEBA"
2,alexandria egypt,2022-01-03,20.1,13.0,15.8,20.1,13.0,15.8,12.0,78.7,...,11.8,6,NaN,2022-01-03T06:59:33,2022-01-03T17:10:14,0.02,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"62318099999,62360199999,HEAX,HEBA"
3,alexandria egypt,2022-01-04,18.1,12.0,15.4,18.1,12.0,15.4,11.2,76.4,...,9.8,5,NaN,2022-01-04T06:59:43,2022-01-04T17:10:59,0.05,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"62318099999,62360199999,HEAX,HEBA"
4,alexandria egypt,2022-01-05,19.9,9.0,14.6,19.9,7.3,14.6,10.4,75.2,...,12.9,6,NaN,2022-01-05T06:59:51,2022-01-05T17:11:45,0.09,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"62318099999,62360199999,HEAX,HEBA"

In [5]:
energy_df.head()

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,alexandria egypt,2022-01-01,17.0,6.0,11.8,17.0,6.0,11.8,10.0,88.1,...,12.2,6,NaN,2022-01-01T06:59:09,2022-01-01T17:08:45,0.95,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,"62318099999,62360199999,HEAX,HEBA"
1,alexandria egypt,2022-01-02,19.0,9.0,14.3,19.0,7.6,14.2,11.4,83.7,...,9.6,5,NaN,2022-01-02T06:59:22,2022-01-02T17:09:29,0.00,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"62318099999,62360199999,HEAX,HEBA"
2,alexandria egypt,2022-01-03,20.1,13.0,15.8,20.1,13.0,15.8,12.0,78.7,...,11.8,6,NaN,2022-01-03T06:59:33,2022-01-03T17:10:14,0.02,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"62318099999,62360199999,HEAX,HEBA"
3,alexandria egypt,2022-01-04,18.1,12.0,15.4,18.1,12.0,15.4,11.2,76.4,...,9.8,5,NaN,2022-01-04T06:59:43,2022-01-04T17:10:59,0.05,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"62318099999,62360199999,HEAX,HEBA"
4,alexandria egypt,2022-01-05,19.9,9.0,14.6,19.9,7.3,14.6,10.4,75.2,...,12.9,6,NaN,2022-01-05T06:59:51,2022-01-05T17:11:45,0.09,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"62318099999,62360199999,HEAX,HEBA"